version: '3.3'
services:

  mysql:
      image: mysql:8.0
      command: mysqld --default-authentication-plugin=mysql_native_password
      ports: 
          - 3306: 3306
      environment: # 環境變數, 設置 db, user, password, root_password
          MYSQL_DATABASE: mydb
          MYSQL_USER: user
          MYSQL_PASSWORD: test
          MYSQL_ROOT_PASSWORD: test
      volumes:
          - mysql:/var/lib/mysql
      networks:
          - dev
  phpmyadmin:
      image: phpmyadmin/phpmyadmin: 5.1.0
      links: 
          - mysql: db
      ports:
          - 8000:80
      depends_on:
        - mysql
      networks:
          - dev
volumes: 
  mysql: 
    external: true
